"""
FA field metadata mappings for CF-compliant attributes.
Comprehensive mapping based on ARPEGE/AROME documentation.
"""

FA_METADATA = {
    '(not specified)': {'long_name': 'Mass change rate in phys.', 'units': '1'},
    '100M.UWIND': {'long_name': '100M U-wind', 'units': 'm s-1'},
    '100M.VWIND': {'long_name': '100M V-wind', 'units': 'm s-1'},
    '100M.WIND.SPEED': {'long_name': '100M Wind Speed', 'units': 'm s-1'},
    '100M_UWIND': {'long_name': '100M U-wind', 'units': 'm s-1'},
    '100M_VWIND': {'long_name': '100M V-wind', 'units': 'm s-1'},
    '100M_WIND_SPEED': {'long_name': '100M Wind Speed', 'units': 'm s-1'},
    '10M.NEUTRL UWIND': {'long_name': '10M Neutral U-wind', 'units': 'm s-1'},
    '10M.NEUTRL VWIND': {'long_name': '10M Neutral V-wind', 'units': 'm s-1'},
    '10M_NEUTRL UWIND': {'long_name': '10M Neutral U-wind', 'units': 'm s-1'},
    '10M_NEUTRL VWIND': {'long_name': '10M Neutral V-wind', 'units': 'm s-1'},
    '200M.UWIND': {'long_name': '200M U-wind', 'units': 'm s-1'},
    '200M.VWIND': {'long_name': '200M V-wind', 'units': 'm s-1'},
    '200M.WIND.SPEED': {'long_name': '200M Wind Speed', 'units': 'm s-1'},
    '200M_UWIND': {'long_name': '200M U-wind', 'units': 'm s-1'},
    '200M_VWIND': {'long_name': '200M V-wind', 'units': 'm s-1'},
    '200M_WIND_SPEED': {'long_name': '200M Wind Speed', 'units': 'm s-1'},
    '20degC depth': {'long_name': 'Ocean depth of 20degC isotherm', 'units': '1'},
    'ABS_VORTICIT': {'long_name': 'Absolute Vorticity', 'units': 's-1'},
    'AERO01-04': {'long_name': 'Aerosol nr 01-04', 'units': '1'},
    'AGAIN.SURF.PRESS': {'long_name': 'Surface pressure', 'units': 'Pa'},
    'AGAIN_SURF_PRESS': {'long_name': 'Surface pressure', 'units': 'Pa'},
    'ATMOHUMI LIQUIDE': {'long_name': 'Liquid specific moisture', 'units': '1'},
    'ATMOHUMI SOLIDE': {'long_name': 'Solid specific moisture', 'units': '1'},
    'ATMOHUMI TOTALE': {'long_name': 'Total precipitable water', 'units': '1'},
    'ATMONEBUL.BASSE': {'long_name': 'Low Cloud Cover', 'units': '1'},
    'ATMONEBUL.CONVEC': {'long_name': 'Convective Cloud Cover', 'units': '1'},
    'ATMONEBUL.HAUTE': {'long_name': 'High Cloud Cover', 'units': '1'},
    'ATMONEBUL.MOYENN': {'long_name': 'Medium Cloud Cover', 'units': '1'},
    'ATMONEBUL.TOTALE': {'long_name': 'Total Cloud cover', 'units': '1'},
    'ATMONEBUL_BASSE': {'long_name': 'Low Cloud Cover', 'units': '1'},
    'ATMONEBUL_CONVEC': {'long_name': 'Convective Cloud Cover', 'units': '1'},
    'ATMONEBUL_HAUTE': {'long_name': 'High Cloud Cover', 'units': '1'},
    'ATMONEBUL_MOYENN': {'long_name': 'Medium Cloud Cover', 'units': '1'},
    'ATMONEBUL_TOTALE': {'long_name': 'Total Cloud cover', 'units': '1'},
    'ATMOOZONE TOTALE': {'long_name': 'Total Ozone', 'units': 'kg kg-1'},
    'C-S PHO.ACT. RAD': {'long_name': 'Surface clear-sky PARadiation', 'units': 'W m-2'},
    'C-S PHO_ACT_ RAD': {'long_name': 'Surface clear-sky PARadiation', 'units': 'W m-2'},
    'C001-002_METEOSAT_07': {'long_name': 'MSAT7 MVIRI CH 1-2', 'units': '1'},
    'C001-004_GOES_11_IMA': {'long_name': 'GOES11 IMAGER CH 1-4', 'units': '1'},
    'C001-004_GOES_12_IMA': {'long_name': 'GOES12 IMAGER CH 1-4', 'units': '1'},
    'C001-004_MTSAT_01_IM': {'long_name': 'MTSAT 1 IMAGER CH 1-4', 'units': '1'},
    'C001-008_METEOSAT_08': {'long_name': 'MSAT8 SEVIRI CH 1-8', 'units': '1'},
    'C001-008_METEOSAT_09': {'long_name': 'MSAT9 SEVIRI CH 1-8', 'units': '1'},
    'CAPE-SHEAR': {'long_name': 'CAPE-Shear', 'units': 'J kg-1'},
    'CG.LIGHTN.AVG 3H': {'long_name': '3h avg. CTG lightning density', 'units': '1'},
    'CG.LIGHTN.AVG 6H': {'long_name': '6h avg. CTG lightning density', 'units': '1'},
    'CG.LIGHTN.AVG1H': {'long_name': '1h avg. CTG lightning density', 'units': '1'},
    'CG.LIGHTN.INST': {'long_name': 'Inst. CTG lightning density', 'units': '1'},
    'CG_LIGHTN_AVG 3H': {'long_name': '3h avg. CTG lightning density', 'units': '1'},
    'CG_LIGHTN_AVG 6H': {'long_name': '6h avg. CTG lightning density', 'units': '1'},
    'CG_LIGHTN_AVG1H': {'long_name': '1h avg. CTG lightning density', 'units': '1'},
    'CG_LIGHTN_INST': {'long_name': 'Inst. CTG lightning density', 'units': '1'},
    'CHEM001-004': {'long_name': 'CHEM var nr 01-04', 'units': '1'},
    'CLD_WX': {'long_name': 'Maximum of CLWC', 'units': '1'},
    'CLD_WX_60M': {'long_name': 'Maximum of CLWC (60min)', 'units': '1'},
    'CLOUD_FRACTI': {'long_name': 'Cloud fraction', 'units': '1'},
    'CLPMHAUT.MOD.XFU': {'long_name': 'Height of the PBL', 'units': 'm'},
    'CLPMHAUT.POS': {'long_name': 'Height of the PBL', 'units': 'm'},
    'CLPMHAUT_MOD_XFU': {'long_name': 'Height of the PBL', 'units': 'm'},
    'CLPMHAUT_POS': {'long_name': 'Height of the PBL', 'units': 'm'},
    'CLPMOCON.MOD.XFU': {'long_name': 'MOCON from the model', 'units': '1'},
    'CLPMOCON.POS': {'long_name': 'MOCON', 'units': '1'},
    'CLPMOCON_MOD_XFU': {'long_name': 'MOCON from the model', 'units': '1'},
    'CLPMOCON_POS': {'long_name': 'MOCON', 'units': '1'},
    'CLPTOPCONV.MOD.X': {'long_name': 'Pressure of top of convection', 'units': 'Pa'},
    'CLPTOPCONV_MOD_X': {'long_name': 'Pressure of top of convection', 'units': 'Pa'},
    'CLPVEIND.MOD.XFU': {'long_name': 'Ventilation Index', 'units': '1'},
    'CLPVEIND.POS': {'long_name': 'Ventilation Index', 'units': '1'},
    'CLPVEIND_MOD_XFU': {'long_name': 'Ventilation Index', 'units': '1'},
    'CLPVEIND_POS': {'long_name': 'Ventilation Index', 'units': '1'},
    'CLSHU.RELATI.POS': {'long_name': 'HU cls (relative humidity)', 'units': '1'},
    'CLSHU.SPECIF.POS': {'long_name': 'Q cls (specific humidity)', 'units': '1'},
    'CLSHUMI.RELATIVE': {'long_name': 'Relative Humidity at PBL height', 'units': 'kg kg-1'},
    'CLSHUMI.SPECIFIQ': {'long_name': 'Specific Humidity at PBL height', 'units': 'kg kg-1'},
    'CLSHUMI_RELATIVE': {'long_name': 'Relative Humidity at PBL height', 'units': 'kg kg-1'},
    'CLSHUMI_SPECIFIQ': {'long_name': 'Specific Humidity at PBL height', 'units': 'kg kg-1'},
    'CLSHU_RELATI_POS': {'long_name': 'HU cls (relative humidity)', 'units': '1'},
    'CLSHU_SPECIF_POS': {'long_name': 'Q cls (specific humidity)', 'units': '1'},
    'CLSMAXI.HUMI.REL': {'long_name': 'Max. rel. moisture at PBL height', 'units': '1'},
    'CLSMAXI.TEMPERAT': {'long_name': 'Maximum temperature at PBL height', 'units': 'K'},
    'CLSMAXI_HUMI_REL': {'long_name': 'Max. rel. moisture at PBL height', 'units': '1'},
    'CLSMAXI_TEMPERAT': {'long_name': 'Maximum temperature at PBL height', 'units': 'K'},
    'CLSMEAN.RAD.TEMP': {'long_name': 'Mean radiant temperature', 'units': 'K'},
    'CLSMEAN_RAD_TEMP': {'long_name': 'Mean radiant temperature', 'units': 'K'},
    'CLSMINI.HUMI.REL': {'long_name': 'Min. rel. moisture at PBL height', 'units': '1'},
    'CLSMINI.TEMPERAT': {'long_name': 'Minimum temperature at PBL height', 'units': 'K'},
    'CLSMINI_HUMI_REL': {'long_name': 'Min. rel. moisture at PBL height', 'units': '1'},
    'CLSMINI_TEMPERAT': {'long_name': 'Minimum temperature at PBL height', 'units': 'K'},
    'CLSPTYPE': {'long_name': 'Precipitation Type', 'units': 'kg m-2'},
    'CLSPTYPESEV': {'long_name': 'Severe Precipitation Type', 'units': 'kg m-2'},
    'CLSPTYPE_60M': {'long_name': 'Precipitation Type (60min)', 'units': 'kg m-2'},
    'CLSRAFAL.MOD.XFU': {'long_name': 'Gusts from the model', 'units': '1'},
    'CLSRAFALES.POS': {'long_name': 'Module of gusts', 'units': '1'},
    'CLSRAFALES_POS': {'long_name': 'Module of gusts', 'units': '1'},
    'CLSRAFAL_MOD_XFU': {'long_name': 'Gusts from the model', 'units': '1'},
    'CLSTEMPERATU.POS': {'long_name': 'T cls', 'units': '1'},
    'CLSTEMPERATURE': {'long_name': 'Temperature at PBL height', 'units': 'K'},
    'CLSTEMPERATU_POS': {'long_name': 'T cls', 'units': '1'},
    'CLSTPRIM_W': {'long_name': 'Wet bulb temperature at 2m', 'units': 'K'},
    'CLSU.RAF2.MOD.XF': {'long_name': 'U-momentum of gusts2', 'units': '1'},
    'CLSU.RAF60M.XFU': {'long_name': 'U-momentum of gusts (60min)', 'units': '1'},
    'CLSURAFALES.POS': {'long_name': 'U gusts', 'units': '1'},
    'CLSURAFALES_POS': {'long_name': 'U gusts', 'units': '1'},
    'CLSU_RAF2_MOD_XF': {'long_name': 'U-momentum of gusts2', 'units': '1'},
    'CLSU_RAF60M_XFU': {'long_name': 'U-momentum of gusts (60min)', 'units': '1'},
    'CLSV.RAF2.MOD.XF': {'long_name': 'V-momentum of gusts2', 'units': '1'},
    'CLSV.RAF60M.XFU': {'long_name': 'V-momentum of gusts (60min)', 'units': '1'},
    'CLSVENT.MERIDIEN': {'long_name': 'V-component of wind at PBL', 'units': 'm s-1'},
    'CLSVENT.ZONAL': {'long_name': 'U-component of wind at PBL', 'units': 'm s-1'},
    'CLSVENTNEUTRE.U': {'long_name': 'U-neutral wind at PBL height', 'units': 'm s-1'},
    'CLSVENTNEUTRE.V': {'long_name': 'V-neutral wind at PBL height', 'units': 'm s-1'},
    'CLSVENTNEUTRE_U': {'long_name': 'U-neutral wind at PBL height', 'units': 'm s-1'},
    'CLSVENTNEUTRE_V': {'long_name': 'V-neutral wind at PBL height', 'units': 'm s-1'},
    'CLSVENT_MERI.POS': {'long_name': 'V cls', 'units': '1'},
    'CLSVENT_MERIDIEN': {'long_name': 'V-component of wind at PBL', 'units': 'm s-1'},
    'CLSVENT_MERI_POS': {'long_name': 'V cls', 'units': '1'},
    'CLSVENT_ZONA.POS': {'long_name': 'U cls', 'units': '1'},
    'CLSVENT_ZONAL': {'long_name': 'U-component of wind at PBL', 'units': 'm s-1'},
    'CLSVENT_ZONA_POS': {'long_name': 'U cls', 'units': '1'},
    'CLSVISIHYDN': {'long_name': 'Visibility due to Precipitation', 'units': 'kg m-2'},
    'CLSVISIHYDN60': {'long_name': 'Visibility due to Precipitation (60min)', 'units': 'kg m-2'},
    'CLSVISIN': {'long_name': 'Visibility due to water/ice', 'units': 'm'},
    'CLSVISIN_60': {'long_name': 'Visibility due to water/ice (60min)', 'units': 'm'},
    'CLSVRAFALES.POS': {'long_name': 'V gusts', 'units': '1'},
    'CLSVRAFALES_POS': {'long_name': 'V gusts', 'units': '1'},
    'CLSV_RAF2_MOD_XF': {'long_name': 'V-momentum of gusts2', 'units': '1'},
    'CLSV_RAF60M_XFU': {'long_name': 'V-momentum of gusts (60min)', 'units': '1'},
    'CLSWIND.VELOCITY': {'long_name': 'Wind intensity at PBL height', 'units': 'm s-1'},
    'CLSWIND_VELO.POS': {'long_name': 'Module of wind cls', 'units': 'm s-1'},
    'CLSWIND_VELOCITY': {'long_name': 'Wind intensity at PBL height', 'units': 'm s-1'},
    'CLSWIND_VELO_POS': {'long_name': 'Module of wind cls', 'units': 'm s-1'},
    'CONV.AV.POT.ENER': {'long_name': 'Conv. Available Potential Energy', 'units': 'm2 s-2'},
    'CONV_AV_POT_ENER': {'long_name': 'Conv. Available Potential Energy', 'units': 'm2 s-2'},
    'CUF1-5PRESSURE': {'long_name': 'Filtered ln(Ps), NCUFNR=1-5', 'units': '1'},
    'CV_PREC_FLUX': {'long_name': 'Convective precip. flux', 'units': 'J m-2'},
    'CalciteFraction1': {'long_name': 'Calcite Fraction 1 (small)', 'units': '1'},
    'CalciteFraction2': {'long_name': 'Calcite Fraction 2 (large)', 'units': '1'},
    'Clear BrightTemp': {'long_name': 'Clear-sky brightness temperature', 'units': 'K'},
    'Cloud BrightTemp': {'long_name': 'Cloudy brightness temperature', 'units': 'K'},
    'DD_MESH_FRAC': {'long_name': 'DD Mesh Fraction', 'units': '1'},
    'DD_OMEGA': {'long_name': 'DD Vertical Velocity', 'units': '1'},
    'DIVERGENCE': {'long_name': 'Divergence', 'units': 's-1'},
    'Duct Base Height': {'long_name': 'Duct Base Height', 'units': 'm'},
    'ECHOTOP': {'long_name': 'Pressure of echotop', 'units': 'Pa'},
    'EDR': {'long_name': 'Eddy diffusivity rate', 'units': '1'},
    'EFB1': {'long_name': 'First variable EFB scheme', 'units': '1'},
    'EFB2': {'long_name': 'Second variable EFB scheme', 'units': '1'},
    'EFB3': {'long_name': 'Third variable EFB scheme', 'units': '1'},
    'ETADOT': {'long_name': 'Etadot', 'units': '1'},
    'EXTGFL.02-03': {'long_name': 'Passive scalar nr 02-03', 'units': '1'},
    'EXTGFL_02-03': {'long_name': 'Passive scalar nr 02-03', 'units': '1'},
    'EZDIAG01-04': {'long_name': 'EZDIAG nr 01-04', 'units': '1'},
    'FONC.COURANT': {'long_name': 'Stream function', 'units': '1'},
    'FONC_COURANT': {'long_name': 'Stream function', 'units': '1'},
    'FRICT. VELOCITY': {'long_name': 'Friction Velocity', 'units': '1'},
    'FRICT_ VELOCITY': {'long_name': 'Friction Velocity', 'units': '1'},
    'GEOMASK.FPOS': {'long_name': 'Mask extra domain', 'units': '1'},
    'GEOMASK_FPOS': {'long_name': 'Mask extra domain', 'units': '1'},
    'GEOPOTENTIEL': {'long_name': 'Geopotential', 'units': 'm2 s-2'},
    'GHG01-03': {'long_name': 'GHG nr 01-03', 'units': '1'},
    'GRAUPEL': {'long_name': 'Atmospheric graupel', 'units': '1'},
    'HAIL': {'long_name': 'Atmospheric hail', 'units': '1'},
    'HUMI.SPECIFI': {'long_name': 'Specific humidity', 'units': '1'},
    'HUMID_DENSIT': {'long_name': 'Humid density', 'units': '1'},
    'HUMI_RELATIV': {'long_name': 'Relative humidity', 'units': '1'},
    'HUMI_SPECIFI': {'long_name': 'Specific humidity', 'units': '1'},
    'ICAOTROP.PRESSUR': {'long_name': 'ICAO Tropopause pressure', 'units': 'Pa'},
    'ICAOTROP.TEMPERA': {'long_name': 'ICAO Tropo. temperature', 'units': 'K'},
    'ICAOTROP_PRESSUR': {'long_name': 'ICAO Tropopause pressure', 'units': 'Pa'},
    'ICAOTROP_TEMPERA': {'long_name': 'ICAO Tropo. temperature', 'units': 'K'},
    'INTSURFGEOPOTENT': {'long_name': 'INTERPOLATED gp orography', 'units': '1'},
    'INTSURFGZ0.THERM': {'long_name': 'Interpolated thermal surf roughness', 'units': '1'},
    'INTSURFGZ0_THERM': {'long_name': 'Interpolated thermal surf roughness', 'units': '1'},
    'INTSURFTEMPERATU': {'long_name': 'INTERPOLATED Ts', 'units': '1'},
    'INTSURFZ0.FOIS.G': {'long_name': 'Interpolated dynamic surf roughness', 'units': '1'},
    'INTSURFZ0_FOIS_G': {'long_name': 'Interpolated dynamic surf roughness', 'units': '1'},
    'ISOT_ALTIT': {'long_name': 'altitude of iso-t', 'units': '1'},
    'ISOT_PRESS': {'long_name': 'Pressure of iso-t', 'units': 'Pa'},
    'Ice thickness': {'long_name': 'Sea ice thickness', 'units': '1'},
    'JETPRESSURE': {'long_name': 'ICAO jet pressure', 'units': 'Pa'},
    'JETVENT_MERIDIEN': {'long_name': 'V-momentum of ICAO jet', 'units': '1'},
    'JETVENT_ZONAL': {'long_name': 'U-momentum of ICAO jet', 'units': '1'},
    'LIQUID_WATER': {'long_name': 'Atmospheric liquid water', 'units': '1'},
    'MAP_FACTOR': {'long_name': 'Map factor', 'units': '1'},
    'MAX CAPE LAST 6H': {'long_name': 'Max CAPE last 6H', 'units': 'J kg-1'},
    'MAX CAPESHEAR 6H': {'long_name': 'Max CAPE-Shear last 6H', 'units': 'J kg-1'},
    'MIXING_LENGTH': {'long_name': 'Prognostic mixing length', 'units': '1'},
    'MONTGOMERY G': {'long_name': 'Montgomery potential', 'units': '1'},
    'MSLPRESSURE': {'long_name': 'Mean sea level pressure', 'units': 'Pa'},
    'MSL_NHPRESSURE': {'long_name': 'MSL NH pressure', 'units': 'Pa'},
    'MY3DFLUX': {'long_name': 'Passive scalar nr 01', 'units': '1'},
    'Mean Refrac Grad': {'long_name': 'Mean Refractivity Gradient', 'units': '1'},
    'Min Refrac Grad': {'long_name': 'Min. Refractivity Gradient', 'units': '1'},
    'Mixed Layer Dep': {'long_name': 'Ocean mixed layer depth', 'units': '1'},
    'OZONE': {'long_name': 'Ozone', 'units': 'kg kg-1'},
    'PHOTO.ACTIVE.RAD': {'long_name': 'Surface PARadiation', 'units': 'W m-2'},
    'PHOTO_ACTIVE_RAD': {'long_name': 'Surface PARadiation', 'units': 'W m-2'},
    'POT.VITESSE': {'long_name': 'Velocity potential', 'units': '1'},
    'POT_VITESSE': {'long_name': 'Velocity potential', 'units': '1'},
    'POT_VORTICIT': {'long_name': 'Potential Vorticity', 'units': 's-1'},
    'PRESS.DEPART': {'long_name': 'Pressure Departure', 'units': 'Pa'},
    'PRESSURE': {'long_name': 'Pressure', 'units': 'Pa'},
    'PRESS_DEPART': {'long_name': 'Pressure Departure', 'units': 'Pa'},
    'PROFPROP.RMAX.EA': {'long_name': 'Clim. rel. deep soil wetness', 'units': '1'},
    'PROFPROP_RMAX_EA': {'long_name': 'Clim. rel. deep soil wetness', 'units': '1'},
    'PROFRESERV.EAU': {'long_name': 'Deep soil wetness', 'units': '1'},
    'PROFRESERV.GLACE': {'long_name': 'Frozen deep soil wetness', 'units': '1'},
    'PROFRESERV_EAU': {'long_name': 'Deep soil wetness', 'units': '1'},
    'PROFRESERV_GLACE': {'long_name': 'Frozen deep soil wetness', 'units': '1'},
    'PROFRUISSELLEMEN': {'long_name': 'Deep soil water content run-off', 'units': '1'},
    'PROFTEMPERATURE': {'long_name': 'Deep soil temperature', 'units': 'K'},
    'PSHI_CONV_CLOUD': {'long_name': 'Cnv pseudohist cloud frac', 'units': '1'},
    'Q SRC TERM TURB': {'long_name': 'Flux Q source term turbul', 'units': 'J m-2'},
    'QI_CONV': {'long_name': 'Convective Solid Water', 'units': '1'},
    'QL_CONV': {'long_name': 'Convective Liquid Water', 'units': '1'},
    'QNHPRESSURE': {'long_name': 'QNH pressure', 'units': 'Pa'},
    'QR_CONV': {'long_name': 'Convective Rain', 'units': '1'},
    'QS_CONV': {'long_name': 'Convective Snow', 'units': 'kg m-2'},
    'RAD_LIQUID_WATER': {'long_name': 'Atmos total liquid water', 'units': '1'},
    'RAD_SOLID_WATER': {'long_name': 'Atmos total solid water', 'units': '1'},
    'RAIN': {'long_name': 'Atmospheric rain', 'units': '1'},
    'REFLECT_DBZ.MAX': {'long_name': 'Maxi. simu. reflect (dBZ)', 'units': 'mm h-1'},
    'REFLECT_DBZ_MAX': {'long_name': 'Maxi. simu. reflect (dBZ)', 'units': 'mm h-1'},
    'REFLEC_DBZ': {'long_name': 'Simulated reflect. in dBz', 'units': 'mm h-1'},
    'RELAPROP.RMAX.EA': {'long_name': 'Relax. deep soil wetness', 'units': '1'},
    'RELAPROP_RMAX_EA': {'long_name': 'Relax. deep soil wetness', 'units': '1'},
    'RK_QCTEND': {'long_name': 'RK scheme condens tend', 'units': '1'},
    'RK_QVTEND': {'long_name': 'RK scheme vapor tend', 'units': '1'},
    'RK_TEMPTEND': {'long_name': 'RK scheme temper tend', 'units': '1'},
    'S SRC TERM TURB': {'long_name': 'Flux S source term turbul', 'units': 'J m-2'},
    'S000FL.CT CONVEC': {'long_name': 'Contribution of Convection to CT', 'units': '1'},
    'S000FL.CT TURBUL': {'long_name': 'Contribution of Turbulence to CT', 'units': '1'},
    'S000FL.Q CONVEC': {'long_name': 'Contribution of Convection to Q', 'units': '1'},
    'S000FL.Q TURBUL': {'long_name': 'Contribution of Turbulence to Q', 'units': '1'},
    'S000FL.U CONVEC': {'long_name': 'Contribution of Convection to U', 'units': '1'},
    'S000FL.U ONDG.OR': {'long_name': 'Contribution of GWD to U', 'units': '1'},
    'S000FL.U TURBUL': {'long_name': 'Contribution of Turbulence to U', 'units': '1'},
    'S000FL.V CONVEC': {'long_name': 'Contribution of Convection to V', 'units': '1'},
    'S000FL.V ONDG.OR': {'long_name': 'Contribution of GWD to V', 'units': '1'},
    'S000FL.V TURBUL': {'long_name': 'Contribution of Turbulence to V', 'units': '1'},
    'S000FL_CT CONVEC': {'long_name': 'Contribution of Convection to CT', 'units': '1'},
    'S000FL_CT TURBUL': {'long_name': 'Contribution of Turbulence to CT', 'units': '1'},
    'S000FL_Q CONVEC': {'long_name': 'Contribution of Convection to Q', 'units': '1'},
    'S000FL_Q TURBUL': {'long_name': 'Contribution of Turbulence to Q', 'units': '1'},
    'S000FL_U CONVEC': {'long_name': 'Contribution of Convection to U', 'units': '1'},
    'S000FL_U ONDG_OR': {'long_name': 'Contribution of GWD to U', 'units': '1'},
    'S000FL_U TURBUL': {'long_name': 'Contribution of Turbulence to U', 'units': '1'},
    'S000FL_V CONVEC': {'long_name': 'Contribution of Convection to V', 'units': '1'},
    'S000FL_V ONDG_OR': {'long_name': 'Contribution of GWD to V', 'units': '1'},
    'S000FL_V TURBUL': {'long_name': 'Contribution of Turbulence to V', 'units': '1'},
    'S000GRAUP CONVEC': {'long_name': 'Convective Graupel Fall', 'units': 'kg m-2'},
    'S000GRAUP STRATI': {'long_name': 'Large Scale Graupel fall', 'units': 'kg m-2'},
    'S000GRELE CONVEC': {'long_name': 'Convective Hail Fall', 'units': 'kg m-2'},
    'S000GRELE STRATI': {'long_name': 'Large Scale Hail fall', 'units': 'kg m-2'},
    'S000NEIGE CONVEC': {'long_name': 'Convective Snow Fall', 'units': 'kg m-2'},
    'S000NEIGE STRATI': {'long_name': 'Large Scale Snow fall', 'units': 'kg m-2'},
    'S000PLUIE STRATI': {'long_name': 'Large Scale (Stratiform) Precipitation', 'units': 'kg m-2'},
    'S000RAYT.SOLAIRE': {'long_name': 'Surface solar radiation', 'units': 'W m-2'},
    'S000RAYT.TERREST': {'long_name': 'Surface Thermal radiation', 'units': 'W m-2'},
    'S000RAYT_SOLAIRE': {'long_name': 'Surface solar radiation', 'units': 'W m-2'},
    'S000RAYT_TERREST': {'long_name': 'Surface Thermal radiation', 'units': 'W m-2'},
    'SD FILTERED OROG': {'long_name': 'SD Filtered Orography', 'units': '1'},
    'SEASURFTEMPERATU': {'long_name': 'Sea Surface Temperature', 'units': 'K'},
    'SF.TOT.SKY DIRDP': {'long_name': 'Surf.tot sky direct beam', 'units': '1'},
    'SF_TOT_SKY DIRDP': {'long_name': 'Surf.tot sky direct beam', 'units': '1'},
    'SHEAR TERM TURB': {'long_name': 'Shear source term turbul.', 'units': '1'},
    'SHEAR_DEFORM': {'long_name': 'Shearing Deformation', 'units': '1'},
    'SIM_REFLECTI': {'long_name': 'Simulated reflect. in mm/h', 'units': 'mm h-1'},
    'SNOW': {'long_name': 'Atmospheric snow', 'units': '1'},
    'SNOW DENSITY': {'long_name': 'Snow density', 'units': 'kg m-2'},
    'SOLID_WATER': {'long_name': 'Atmospheric solid water', 'units': '1'},
    'SOMMFLU.RAY.SOLA': {'long_name': 'Top Solar radiation', 'units': 'W m-2'},
    'SOMMFLU.RAY.THER': {'long_name': 'Top Thermal radiation', 'units': 'W m-2'},
    'SOMMFLU_RAY_SOLA': {'long_name': 'Top Solar radiation', 'units': 'W m-2'},
    'SOMMFLU_RAY_THER': {'long_name': 'Top Thermal radiation', 'units': 'W m-2'},
    'SOMMRAYT SOL CL': {'long_name': 'Top clear sky shortwave radiation', 'units': 'W m-2'},
    'SOMMRAYT THER CL': {'long_name': 'Top clear sky longwave radiation', 'units': 'W m-2'},
    'SOMMRAYT.SOLAIRE': {'long_name': 'Top Solar radiation', 'units': 'W m-2'},
    'SOMMRAYT.TERREST': {'long_name': 'Top Thermal radiation', 'units': 'W m-2'},
    'SOMMRAYT_SOLAIRE': {'long_name': 'Top Solar radiation', 'units': 'W m-2'},
    'SOMMRAYT_TERREST': {'long_name': 'Top Thermal radiation', 'units': 'W m-2'},
    'SPECSURFGEOPOTEN': {'long_name': 'Surface geopotential', 'units': '1'},
    'STORMMOTIONU': {'long_name': 'Storm motion, u component', 'units': '1'},
    'STORMMOTIONV': {'long_name': 'Storm motion, v component', 'units': '1'},
    'STORMRELHELICITY': {'long_name': 'Storm relative helicity', 'units': '1'},
    'STRET_DEFORM': {'long_name': 'Stretching Deformation', 'units': '1'},
    'ST_PREC_FLUX': {'long_name': 'Stratiform precip. flux', 'units': 'J m-2'},
    'SUNSHI. DURATION': {'long_name': 'Sunshine Duration', 'units': 's'},
    'SUNSHI_ DURATION': {'long_name': 'Sunshine Duration', 'units': 's'},
    'SUR.CLR-SKY DIRD': {'long_name': 'Surf.clear-sky direct SW', 'units': '1'},
    'SUR.TOT.SKY DIRD': {'long_name': 'Surf.total sky direct SW', 'units': '1'},
    'SURF.U.ANISO.DIR': {'long_name': 'Anisotropy vector/U-momentum', 'units': '1'},
    'SURF.V.ANISO.DIR': {'long_name': 'Anisotropy vector/V-momentum', 'units': '1'},
    'SURF2D.01-03': {'long_name': 'Free surface field nr 01-03', 'units': '1'},
    'SURF2D_01-03': {'long_name': 'Free surface field nr 01-03', 'units': '1'},
    'SURFA.OF.OZONE': {'long_name': 'First ozone profile (A)', 'units': '1'},
    'SURFACCGRELE': {'long_name': 'Dummy hail field (AROME)', 'units': '1'},
    'SURFACE PRESSURE': {'long_name': 'Surface Pressure', 'units': 'Pa'},
    'SURFAEROS.DESERT': {'long_name': 'Desert aerosols', 'units': '1'},
    'SURFAEROS.LAND': {'long_name': 'Continental aerosols', 'units': '1'},
    'SURFAEROS.SEA': {'long_name': 'Marine aerosols', 'units': '1'},
    'SURFAEROS.SOOT': {'long_name': 'Carbone aerosols', 'units': '1'},
    'SURFAEROS.SULFAT': {'long_name': 'Sulfate aerosols', 'units': '1'},
    'SURFAEROS.VOLCAN': {'long_name': 'Volcano aerosols', 'units': '1'},
    'SURFAEROS_DESERT': {'long_name': 'Desert aerosols', 'units': '1'},
    'SURFAEROS_LAND': {'long_name': 'Continental aerosols', 'units': '1'},
    'SURFAEROS_SEA': {'long_name': 'Marine aerosols', 'units': '1'},
    'SURFAEROS_SOOT': {'long_name': 'Carbone aerosols', 'units': '1'},
    'SURFAEROS_SULFAT': {'long_name': 'Sulfate aerosols', 'units': '1'},
    'SURFAEROS_VOLCAN': {'long_name': 'Volcano aerosols', 'units': '1'},
    'SURFALBEDO': {'long_name': 'Albedo', 'units': '1'},
    'SURFALBEDO HISTO': {'long_name': 'Surf. albedo total', 'units': '1'},
    'SURFALBEDO NEIGE': {'long_name': 'Surface snow albedo', 'units': '1'},
    'SURFALBEDO.COMPL': {'long_name': 'Surf. albedo for non snow', 'units': '1'},
    'SURFALBEDO.SOLNU': {'long_name': 'Surf. albedo for bare ground', 'units': '1'},
    'SURFALBEDO.VEG': {'long_name': 'Surf. albedo for vegetation', 'units': '1'},
    'SURFALBEDO_COMPL': {'long_name': 'Surf. albedo for non snow', 'units': '1'},
    'SURFALBEDO_SOLNU': {'long_name': 'Surf. albedo for bare ground', 'units': '1'},
    'SURFALBEDO_VEG': {'long_name': 'Surf. albedo for vegetation', 'units': '1'},
    'SURFANAMOCON.POS': {'long_name': 'Analysed surface MOCON', 'units': '1'},
    'SURFANAMOCON_POS': {'long_name': 'Analysed surface MOCON', 'units': '1'},
    'SURFA_OF_OZONE': {'long_name': 'First ozone profile (A)', 'units': '1'},
    'SURFB.OF.OZONE': {'long_name': 'Second ozone profile (B)', 'units': '1'},
    'SURFB_OF_OZONE': {'long_name': 'Second ozone profile (B)', 'units': '1'},
    'SURFC.OF.OZONE': {'long_name': 'Third ozone profile (C)', 'units': '1'},
    'SURFCAPE.MOD.XFU': {'long_name': 'CAPE from the model', 'units': 'J kg-1'},
    'SURFCAPE.POS.F00': {'long_name': 'CAPE', 'units': 'J kg-1'},
    'SURFCAPE_MOD_XFU': {'long_name': 'CAPE from the model', 'units': 'J kg-1'},
    'SURFCAPE_POS_F00': {'long_name': 'CAPE', 'units': 'J kg-1'},
    'SURFCFU.CT.CONVE': {'long_name': 'Contrib. of Convection to CT', 'units': '1'},
    'SURFCFU.CT.TURBU': {'long_name': 'Contrib. of Turbulence to CT', 'units': '1'},
    'SURFCFU.Q.CONVEC': {'long_name': 'Contrib. of Convection to Q', 'units': '1'},
    'SURFCFU.Q.TURBUL': {'long_name': 'Contrib. of Turbulence to Q', 'units': '1'},
    'SURFCFU_CT_CONVE': {'long_name': 'Contrib. of Convection to CT', 'units': '1'},
    'SURFCFU_CT_TURBU': {'long_name': 'Contrib. of Turbulence to CT', 'units': '1'},
    'SURFCFU_Q_CONVEC': {'long_name': 'Contrib. of Convection to Q', 'units': '1'},
    'SURFCFU_Q_TURBUL': {'long_name': 'Contrib. of Turbulence to Q', 'units': '1'},
    'SURFCHAL LATENTE': {'long_name': 'Surface Latent Heat Flux', 'units': 'J m-2'},
    'SURFCHAL. DS SOL': {'long_name': 'Flux de chaleur dans le sol', 'units': 'J m-2'},
    'SURFCHAL_ DS SOL': {'long_name': 'Flux de chaleur dans le sol', 'units': 'J m-2'},
    'SURFCIEN.POS.F00': {'long_name': 'CIEN', 'units': '1'},
    'SURFCIEN_POS_F00': {'long_name': 'CIEN', 'units': '1'},
    'SURFCONTENU EAU': {'long_name': 'Soil Moisture', 'units': 'kg m-2'},
    'SURFC_OF_OZONE': {'long_name': 'Third ozone profile (C)', 'units': '1'},
    'SURFDENSIT.NEIGE': {'long_name': 'Surface snow density', 'units': '1'},
    'SURFDENSIT_NEIGE': {'long_name': 'Surface snow density', 'units': '1'},
    'SURFDIAG.FLASH': {'long_name': 'Cumulative lightning density', 'units': '1'},
    'SURFDIAGHAIL': {'long_name': 'Hail Diagnostic (AROME)', 'units': 'kg m-2'},
    'SURFDIAG_FLASH': {'long_name': 'Cumulative lightning density', 'units': '1'},
    'SURFDIR NORM IRR': {'long_name': 'Surface direct normal irradiance', 'units': '1'},
    'SURFDISSIP SURF': {'long_name': 'Boundary Layer Dissipation', 'units': '1'},
    'SURFEAU DANS SOL': {'long_name': 'Flux d\'eau dans le sol', 'units': 'J m-2'},
    'SURFEMISSIVITE': {'long_name': 'Emissivity', 'units': '1'},
    'SURFEPAI.SOL.MAX': {'long_name': 'Maximum soil depth', 'units': '1'},
    'SURFEPAIS.SOL': {'long_name': 'Soil depth', 'units': '1'},
    'SURFEPAIS_SOL': {'long_name': 'Soil depth', 'units': '1'},
    'SURFEPAI_SOL_MAX': {'long_name': 'Maximum soil depth', 'units': '1'},
    'SURFEQUILIBRLEV': {'long_name': 'Equilibrium Level', 'units': '1'},
    'SURFET.GEOPOTENT': {'long_name': 'Std. dev. of orography (*g)', 'units': '1'},
    'SURFETA.GEOPOTEN': {'long_name': 'Analysed RMS of PHI (CANA)', 'units': '1'},
    'SURFETA_GEOPOTEN': {'long_name': 'Analysed RMS of PHI (CANA)', 'units': '1'},
    'SURFETP.GEOPOTEN': {'long_name': 'Forecasted RMS of PHI (CANA)', 'units': '1'},
    'SURFETP_GEOPOTEN': {'long_name': 'Forecasted RMS of PHI (CANA)', 'units': '1'},
    'SURFET_GEOPOTENT': {'long_name': 'Std. dev. of orography (*g)', 'units': '1'},
    'SURFEVAPOTRANSPI': {'long_name': 'Evapotranspiration', 'units': '1'},
    'SURFEXTRAFIELD01-03': {'long_name': 'Extra field n 01-03', 'units': '1'},
    'SURFFLU.CHA.SENS': {'long_name': 'Surface Sensible Heat Flux', 'units': 'J m-2'},
    'SURFFLU.LAT.MEVA': {'long_name': 'Latent Heat Evaporation', 'units': '1'},
    'SURFFLU.LAT.MSUB': {'long_name': 'Latent Heat Sublimation', 'units': '1'},
    'SURFFLU.LAT.MTOT': {'long_name': 'Total Latent Heat (Water)', 'units': '1'},
    'SURFFLU.MEVAP.EA': {'long_name': 'Water Evaporation', 'units': '1'},
    'SURFFLU.MSUBL.NE': {'long_name': 'Snow Sublimation', 'units': 'kg m-2'},
    'SURFFLU.MTOTA.NE': {'long_name': 'Water + Snow Evaporation', 'units': 'kg m-2'},
    'SURFFLU.RAY.SOLA': {'long_name': 'Surface solar radiation', 'units': 'W m-2'},
    'SURFFLU.RAY.THER': {'long_name': 'Surface Thermal radiation', 'units': 'W m-2'},
    'SURFFLU_CHA_SENS': {'long_name': 'Surface Sensible Heat Flux', 'units': 'J m-2'},
    'SURFFLU_LAT_MEVA': {'long_name': 'Latent Heat Evaporation', 'units': '1'},
    'SURFFLU_LAT_MSUB': {'long_name': 'Latent Heat Sublimation', 'units': '1'},
    'SURFFLU_LAT_MTOT': {'long_name': 'Total Latent Heat (Water)', 'units': '1'},
    'SURFFLU_MEVAP_EA': {'long_name': 'Water Evaporation', 'units': '1'},
    'SURFFLU_MSUBL_NE': {'long_name': 'Snow Sublimation', 'units': 'kg m-2'},
    'SURFFLU_MTOTA_NE': {'long_name': 'Water + Snow Evaporation', 'units': 'kg m-2'},
    'SURFFLU_RAY_SOLA': {'long_name': 'Surface solar radiation', 'units': 'W m-2'},
    'SURFFLU_RAY_THER': {'long_name': 'Surface Thermal radiation', 'units': 'W m-2'},
    'SURFFONTE NEIGE': {'long_name': 'Melt snow', 'units': '1'},
    'SURFFREE.FIELD01-03': {'long_name': 'Free field nr 01-03', 'units': '1'},
    'SURFFREECONVLEV': {'long_name': 'Free Convection Level', 'units': '1'},
    'SURFFREE_FIELD01-03': {'long_name': 'Free field nr 01-03', 'units': '1'},
    'SURFGEOPOTENTIEL': {'long_name': 'OUTPUT gp orography (*g)', 'units': '1'},
    'SURFGLB NORM IRR': {'long_name': 'Surface global normal irradiance', 'units': '1'},
    'SURFGZ0.THERM': {'long_name': 'Heat roughness length (*g)', 'units': '1'},
    'SURFGZ0_THERM': {'long_name': 'Heat roughness length (*g)', 'units': '1'},
    'SURFHUMI.RELATIV': {'long_name': 'Surface relative moisture', 'units': '1'},
    'SURFHUMI_RELATIV': {'long_name': 'Surface relative moisture', 'units': '1'},
    'SURFINCREMENT.HN': {'long_name': 'Increment to mini rel. moisture', 'units': '1'},
    'SURFINCREMENT.HX': {'long_name': 'Increment to maxi rel. moisture', 'units': '1'},
    'SURFINCREMENT.TN': {'long_name': 'Increment to mini temperature', 'units': 'K'},
    'SURFINCREMENT.TX': {'long_name': 'Increment to maxi temperature', 'units': 'K'},
    'SURFINCREMENT_HN': {'long_name': 'Increment to mini rel. moisture', 'units': '1'},
    'SURFINCREMENT_HX': {'long_name': 'Increment to maxi rel. moisture', 'units': '1'},
    'SURFINCREMENT_TN': {'long_name': 'Increment to mini temperature', 'units': 'K'},
    'SURFINCREMENT_TX': {'long_name': 'Increment to maxi temperature', 'units': 'K'},
    'SURFIND.FOLIAIRE': {'long_name': 'Leaf area index', 'units': '1'},
    'SURFIND.TERREMER': {'long_name': 'Land/sea mask', 'units': '1'},
    'SURFIND.VEG.DOMI': {'long_name': 'Index of vegetation', 'units': '1'},
    'SURFIND_FOLIAIRE': {'long_name': 'Leaf area index', 'units': '1'},
    'SURFIND_TERREMER': {'long_name': 'Land/sea mask', 'units': '1'},
    'SURFIND_VEG_DOMI': {'long_name': 'Index of vegetation', 'units': '1'},
    'SURFISOTPW0.MALT': {'long_name': 'altitude of iso-tprimw=0', 'units': '1'},
    'SURFISOTPW0_MALT': {'long_name': 'altitude of iso-tprimw=0', 'units': '1'},
    'SURFISOTPW1.MALT': {'long_name': 'altitude of iso-tprimw=1', 'units': '1'},
    'SURFISOTPW1_MALT': {'long_name': 'altitude of iso-tprimw=1', 'units': '1'},
    'SURFISOTPW2.MALT': {'long_name': 'altitude of iso-tpw=1P5', 'units': '1'},
    'SURFISOTPW2_MALT': {'long_name': 'altitude of iso-tpw=1P5', 'units': '1'},
    'SURFLIFTCONDLEV': {'long_name': 'Lifting Condensation Level', 'units': '1'},
    'SURFMOCON.POS': {'long_name': 'Forecasted surface MOCON', 'units': '1'},
    'SURFMOCON_POS': {'long_name': 'Forecasted surface MOCON', 'units': '1'},
    'SURFNEBUL.BASSE': {'long_name': 'Low Cloud Cover', 'units': '1'},
    'SURFNEBUL.CONVEC': {'long_name': 'Convective Cloud Cover', 'units': '1'},
    'SURFNEBUL.HAUTE': {'long_name': 'High Cloud Cover', 'units': '1'},
    'SURFNEBUL.MOYENN': {'long_name': 'Medium Cloud Cover', 'units': '1'},
    'SURFNEBUL.TOTALE': {'long_name': 'Total Cloud cover', 'units': '1'},
    'SURFNEBUL_BASSE': {'long_name': 'Low Cloud Cover', 'units': '1'},
    'SURFNEBUL_CONVEC': {'long_name': 'Convective Cloud Cover', 'units': '1'},
    'SURFNEBUL_HAUTE': {'long_name': 'High Cloud Cover', 'units': '1'},
    'SURFNEBUL_MOYENN': {'long_name': 'Medium Cloud Cover', 'units': '1'},
    'SURFNEBUL_TOTALE': {'long_name': 'Total Cloud cover', 'units': '1'},
    'SURFPREC.EAU.CON': {'long_name': 'Convective precipitation', 'units': '1'},
    'SURFPREC.EAU.GEC': {'long_name': 'Large Scale (Stratiform) Precipitation', 'units': 'kg m-2'},
    'SURFPREC.GRA.CON': {'long_name': 'Convective Graupel Fall', 'units': 'kg m-2'},
    'SURFPREC.GRA.GEC': {'long_name': 'Large Scale Graupel fall', 'units': 'kg m-2'},
    'SURFPREC.GRE.CON': {'long_name': 'Convective Hail Fall', 'units': 'kg m-2'},
    'SURFPREC.GRE.GEC': {'long_name': 'Large Scale Hail fall', 'units': 'kg m-2'},
    'SURFPREC.NEI.CON': {'long_name': 'Convective Snow Fall', 'units': 'kg m-2'},
    'SURFPREC.NEI.GEC': {'long_name': 'Large Scale Snow fall', 'units': 'kg m-2'},
    'SURFPREC_EAU_CON': {'long_name': 'Convective precipitation', 'units': '1'},
    'SURFPREC_EAU_GEC': {'long_name': 'Large Scale (Stratiform) Precipitation', 'units': 'kg m-2'},
    'SURFPREC_GRA_CON': {'long_name': 'Convective Graupel Fall', 'units': 'kg m-2'},
    'SURFPREC_GRA_GEC': {'long_name': 'Large Scale Graupel fall', 'units': 'kg m-2'},
    'SURFPREC_GRE_CON': {'long_name': 'Convective Hail Fall', 'units': 'kg m-2'},
    'SURFPREC_GRE_GEC': {'long_name': 'Large Scale Hail fall', 'units': 'kg m-2'},
    'SURFPREC_NEI_CON': {'long_name': 'Convective Snow Fall', 'units': 'kg m-2'},
    'SURFPREC_NEI_GEC': {'long_name': 'Large Scale Snow fall', 'units': 'kg m-2'},
    'SURFPRESSION': {'long_name': 'Log. of Surface pressure', 'units': 'Pa'},
    'SURFPRESSION SOL': {'long_name': 'Tendency of Surface pressure', 'units': 'Pa'},
    'SURFPROP.ARGILE': {'long_name': 'Percentage of clay in soil', 'units': '1'},
    'SURFPROP.RMAX.EA': {'long_name': 'Clim. rel. surf soil wetness', 'units': '1'},
    'SURFPROP.SABLE': {'long_name': 'Percentage of sand in soil', 'units': '1'},
    'SURFPROP.TERRE': {'long_name': 'Percentage of land', 'units': '1'},
    'SURFPROP.URBANIS': {'long_name': 'Proportion of urbanisation', 'units': '1'},
    'SURFPROP.VEG.MAX': {'long_name': 'Maximum proportion of vegetation', 'units': '1'},
    'SURFPROP.VEGETAT': {'long_name': 'Percentage of vegetation', 'units': '1'},
    'SURFPROP_ARGILE': {'long_name': 'Percentage of clay in soil', 'units': '1'},
    'SURFPROP_RMAX_EA': {'long_name': 'Clim. rel. surf soil wetness', 'units': '1'},
    'SURFPROP_SABLE': {'long_name': 'Percentage of sand in soil', 'units': '1'},
    'SURFPROP_TERRE': {'long_name': 'Percentage of land', 'units': '1'},
    'SURFPROP_URBANIS': {'long_name': 'Proportion of urbanisation', 'units': '1'},
    'SURFPROP_VEGETAT': {'long_name': 'Percentage of vegetation', 'units': '1'},
    'SURFPROP_VEG_MAX': {'long_name': 'Maximum proportion of vegetation', 'units': '1'},
    'SURFRAYT DIR SUR': {'long_name': 'Surface parallel solar flux', 'units': 'J m-2'},
    'SURFRAYT SOL CL': {'long_name': 'Clear sky shortwave radiation', 'units': 'W m-2'},
    'SURFRAYT SOLA DE': {'long_name': 'Surface down solar flux', 'units': 'J m-2'},
    'SURFRAYT THER CL': {'long_name': 'Clear sky longwave radiation', 'units': 'W m-2'},
    'SURFRAYT THER DE': {'long_name': 'Surface down thermic flux', 'units': 'J m-2'},
    'SURFRAYT.LUNE.DE': {'long_name': 'Surface moon radiation', 'units': 'W m-2'},
    'SURFRAYT_LUNE_DE': {'long_name': 'Surface moon radiation', 'units': 'W m-2'},
    'SURFREFLECT.MAX': {'long_name': 'Maxi. simu. reflect (mm/h)', 'units': 'mm h-1'},
    'SURFREFLECT_MAX': {'long_name': 'Maxi. simu. reflect (mm/h)', 'units': 'mm h-1'},
    'SURFRES.EVAPOTRA': {'long_name': 'Resist. to evapotranspiration', 'units': '1'},
    'SURFRESERV NEIGE': {'long_name': 'Snow mass', 'units': 'kg m-2'},
    'SURFRESERV.EAU': {'long_name': 'Surface soil wetness', 'units': '1'},
    'SURFRESERV.GLACE': {'long_name': 'Frozen surface soil wetness', 'units': '1'},
    'SURFRESERV.INTER': {'long_name': 'Interception content', 'units': '1'},
    'SURFRESERV.NEIGE': {'long_name': 'Snow depth', 'units': 'kg m-2'},
    'SURFRESERV_EAU': {'long_name': 'Surface soil wetness', 'units': '1'},
    'SURFRESERV_GLACE': {'long_name': 'Frozen surface soil wetness', 'units': '1'},
    'SURFRESERV_INTER': {'long_name': 'Interception content', 'units': '1'},
    'SURFRESERV_NEIGE': {'long_name': 'Snow depth', 'units': 'kg m-2'},
    'SURFRESI.STO.MIN': {'long_name': 'Stomatal minimum resistance', 'units': '1'},
    'SURFRESI_STO_MIN': {'long_name': 'Stomatal minimum resistance', 'units': '1'},
    'SURFRES_EVAPOTRA': {'long_name': 'Resist. to evapotranspiration', 'units': '1'},
    'SURFRUISS. INTER': {'long_name': 'Interception water content run-off', 'units': '1'},
    'SURFRUISSELLEMEN': {'long_name': 'Surf. water content run-off', 'units': '1'},
    'SURFRUISS_ INTER': {'long_name': 'Interception water content run-off', 'units': '1'},
    'SURFTCVS.POS.F00': {'long_name': 'Temperature of convection', 'units': 'K'},
    'SURFTCVS_POS_F00': {'long_name': 'Temperature of convection', 'units': 'K'},
    'SURFTEMPERATURE': {'long_name': 'Surface temperature', 'units': 'K'},
    'SURFTENS.CONV.ME': {'long_name': 'Contrib. of Convection to V', 'units': '1'},
    'SURFTENS.CONV.ZO': {'long_name': 'Contrib. of Convection to U', 'units': '1'},
    'SURFTENS.DMOG.ME': {'long_name': 'V-Gravity-Wave Stress', 'units': 'N m-2'},
    'SURFTENS.DMOG.ZO': {'long_name': 'U-Gravity-Wave Stress', 'units': 'N m-2'},
    'SURFTENS.TOTA.ME': {'long_name': 'V-Total Stress', 'units': 'N m-2'},
    'SURFTENS.TOTA.ZO': {'long_name': 'U-Total Stress', 'units': 'N m-2'},
    'SURFTENS.TURB.ME': {'long_name': 'V-stress', 'units': '1'},
    'SURFTENS.TURB.ZO': {'long_name': 'U-stress', 'units': '1'},
    'SURFTENS_CONV_ME': {'long_name': 'Contrib. of Convection to V', 'units': '1'},
    'SURFTENS_CONV_ZO': {'long_name': 'Contrib. of Convection to U', 'units': '1'},
    'SURFTENS_DMOG_ME': {'long_name': 'V-Gravity-Wave Stress', 'units': 'N m-2'},
    'SURFTENS_DMOG_ZO': {'long_name': 'U-Gravity-Wave Stress', 'units': 'N m-2'},
    'SURFTENS_TOTA_ME': {'long_name': 'V-Total Stress', 'units': 'N m-2'},
    'SURFTENS_TOTA_ZO': {'long_name': 'U-Total Stress', 'units': 'N m-2'},
    'SURFTENS_TURB_ME': {'long_name': 'V-stress', 'units': '1'},
    'SURFTENS_TURB_ZO': {'long_name': 'U-stress', 'units': '1'},
    'SURFTIME.PREC.TO': {'long_name': 'Duration of total precipitation', 'units': 's'},
    'SURFTIME_PREC_TO': {'long_name': 'Duration of total precipitation', 'units': 's'},
    'SURFTOT.WAT.VAPO': {'long_name': 'Total water vapour', 'units': '1'},
    'SURFTOT_WAT_VAPO': {'long_name': 'Total water vapour', 'units': '1'},
    'SURFTRANSPIRATIO': {'long_name': 'Transpiration', 'units': '1'},
    'SURFVAR.GEOP.ANI': {'long_name': 'Anisotropy of topography', 'units': '1'},
    'SURFVAR.GEOP.DIR': {'long_name': 'Topography main direction', 'units': '1'},
    'SURFVAR_GEOP_ANI': {'long_name': 'Anisotropy of topography', 'units': '1'},
    'SURFVAR_GEOP_DIR': {'long_name': 'Topography main direction', 'units': '1'},
    'SURFVERT.VELOCIT': {'long_name': 'Surface Vertical Velocity', 'units': '1'},
    'SURFVERT_VELOCIT': {'long_name': 'Surface Vertical Velocity', 'units': '1'},
    'SURFZ0.FOIS.G': {'long_name': 'Surface roughness (*g)', 'units': '1'},
    'SURFZ0REL.FOIS.G': {'long_name': 'Roughness length (*g)', 'units': 'm'},
    'SURFZ0REL_FOIS_G': {'long_name': 'Roughness length (*g)', 'units': 'm'},
    'SURFZ0VEG.FOIS.G': {'long_name': 'Vegetation roughness length (*g)', 'units': '1'},
    'SURFZ0VEG_FOIS_G': {'long_name': 'Vegetation roughness length (*g)', 'units': '1'},
    'SURFZ0_FOIS_G': {'long_name': 'Surface roughness (*g)', 'units': '1'},
    'SURF_U_ANISO_DIR': {'long_name': 'Anisotropy vector/U-momentum', 'units': '1'},
    'SURF_V_ANISO_DIR': {'long_name': 'Anisotropy vector/V-momentum', 'units': '1'},
    'SUR_CLR-SKY DIRD': {'long_name': 'Surf.clear-sky direct SW', 'units': '1'},
    'SUR_NHPRESSURE': {'long_name': 'Surface NH pressure', 'units': 'Pa'},
    'SUR_TOT_SKY DIRD': {'long_name': 'Surf.total sky direct SW', 'units': '1'},
    'Sea Surf Height': {'long_name': 'Ocean sea surface height', 'units': '1'},
    'Sea Surf Salini': {'long_name': 'Ocean sea surface salinity', 'units': '1'},
    'TEMPERATURE': {'long_name': 'Temperature', 'units': 'K'},
    'TEMPE_POTENT': {'long_name': 'Potential temperature', 'units': 'K'},
    'THETAPWP_FLUX': {'long_name': 'Thetaprimwprim surface flux', 'units': 'J m-2'},
    'THETA_EQUIVA': {'long_name': 'Equiv. pot. temperature', 'units': 'K'},
    'THETA_PRIM_W': {'long_name': 'Wet bulb pot. temperature', 'units': 'K'},
    'THETA_VIRTUA': {'long_name': 'Virtual Theta', 'units': '1'},
    'TKE': {'long_name': 'Turbulent kinetic energy', 'units': '1'},
    'TOA INC.SOL. RAD': {'long_name': 'TOA incident solar radiation', 'units': 'W m-2'},
    'TOA INC_SOL_ RAD': {'long_name': 'TOA incident solar radiation', 'units': 'W m-2'},
    'TOPMESO ENTH': {'long_name': 'Top mesospheric enthalpy', 'units': '1'},
    'TOPRAYT DIR SOM': {'long_name': 'Top parallel solar flux', 'units': 'J m-2'},
    'TOT.LIGHTN.AVG1H': {'long_name': '1h avg. total lightning density', 'units': '1'},
    'TOT.LIGHTN.AVG3H': {'long_name': '3h avg. total lightning density', 'units': '1'},
    'TOT.LIGHTN.AVG6H': {'long_name': '6h avg. total lightning density', 'units': '1'},
    'TOT.LIGHTN.INST': {'long_name': 'Inst. total lightning density', 'units': '1'},
    'TOTAL_TUR_ENERGY': {'long_name': 'Total turbulent energy', 'units': '1'},
    'TOT_LIGHTN_AVG1H': {'long_name': '1h avg. total lightning density', 'units': '1'},
    'TOT_LIGHTN_AVG3H': {'long_name': '3h avg. total lightning density', 'units': '1'},
    'TOT_LIGHTN_AVG6H': {'long_name': '6h avg. total lightning density', 'units': '1'},
    'TOT_LIGHTN_INST': {'long_name': 'Inst. total lightning density', 'units': '1'},
    'TPRIM_W': {'long_name': 'Wet bulb temperature', 'units': 'K'},
    'TROPO_FOLD_INDIC': {'long_name': 'Tropo. Folding Indicator', 'units': '1'},
    'Trap Layer Base': {'long_name': 'Trapping Layer Base Height', 'units': 'm'},
    'Trap Layer Top': {'long_name': 'Trapping Layer Top Height', 'units': 'm'},
    'UD_ENTRAINMENT': {'long_name': 'UD pseudohist entrainment', 'units': '1'},
    'UD_MESH_FRAC': {'long_name': 'UD Mesh Fraction', 'units': '1'},
    'UD_OMEGA': {'long_name': 'UD Vertical Velocity', 'units': '1'},
    'UPPER_AIR.01-03': {'long_name': 'Free upper air field n 01-03', 'units': '1'},
    'UPPER_AIR_01-03': {'long_name': 'Free upper air field n 01-03', 'units': '1'},
    'UV-B RADIATION': {'long_name': 'Surface UV-B radiation', 'units': 'W m-2'},
    'VARPACKSURFMOCON': {'long_name': 'Surface MOCON for VARPACK', 'units': '1'},
    'VENT_MERIDIE': {'long_name': 'V-momentum of wind', 'units': 'm s-1'},
    'VENT_ZONAL': {'long_name': 'U-momentum of wind', 'units': 'm s-1'},
    'VERT.VELOCIT': {'long_name': 'Vert velocity w=Dz/Dt (m/s)', 'units': 'm s-1'},
    'VERTIC.DIVER': {'long_name': 'Pseudo Vertic. Divergence', 'units': 's-1'},
    'VERTIC_DIVER': {'long_name': 'Pseudo Vertic. Divergence', 'units': 's-1'},
    'VERT_VELOCIT': {'long_name': 'Vert velocity w=Dz/Dt (m/s)', 'units': 'm s-1'},
    'VIRT_P_TEMPE': {'long_name': 'Isobaric equivalent tempe', 'units': '1'},
    'VITESSE_VERT': {'long_name': 'Ver velocity omega=DPi/Dt (Pa/s)', 'units': 'm s-1'},
    'VORTICITY': {'long_name': 'Vorticity', 'units': 's-1'},
    'VertIntegMassDiv': {'long_name': 'Vertically-integr. mass div', 'units': '1'},
    'Volcano Altitude': {'long_name': 'Volcano altitude', 'units': '1'},
    'WIND_VELOCIT': {'long_name': 'Wind velocity', 'units': 'm s-1'},
    # Additional fields found in real data
    'WIND_U_PHYS': {'long_name': 'U Wind Component', 'units': 'm s-1'},
    'WIND_V_PHYS': {'long_name': 'V Wind Component', 'units': 'm s-1'},
    'WIND_U_PHY': {'long_name': 'U Wind Component', 'units': 'm s-1'},
    'WIND_V_PHY': {'long_name': 'V Wind Component', 'units': 'm s-1'},
    'CLSU_RAF_MOD_XFU': {'long_name': 'U Wind Gust', 'units': 'm s-1'},
    'CLSV_RAF_MOD_XFU': {'long_name': 'V Wind Gust', 'units': 'm s-1'},
    'SURFFLU_LAT_TOTA': {'long_name': 'Total Latent Heat Flux', 'units': 'J m-2'},
    'SURFRF_LONG_DO': {'long_name': 'Surface Downward Longwave Radiation', 'units': 'W m-2'},
    'SURFRF_SHORT_DO': {'long_name': 'Surface Downward Shortwave Radiation', 'units': 'W m-2'},
}

PREDEFINED_REGIONS = {
    'france': {'lon_range': (-5, 10), 'lat_range': (41, 52)},
    'alps': {'lon_range': (5, 15), 'lat_range': (44, 48)},
    'pyrenees': {'lon_range': (-2, 3), 'lat_range': (42, 44)},
    'britain': {'lon_range': (-8, 2), 'lat_range': (50, 59)},
    'iberia': {'lon_range': (-10, 4), 'lat_range': (36, 44)},
    'italy': {'lon_range': (6, 19), 'lat_range': (36, 47)},
    'germany': {'lon_range': (5, 16), 'lat_range': (47, 55)},
    'benelux': {'lon_range': (2, 8), 'lat_range': (49, 54)},
    'scandinavia': {'lon_range': (4, 31), 'lat_range': (55, 72)},
    'mediterranean': {'lon_range': (-6, 36), 'lat_range': (30, 46)},
}


def get_metadata(field_name: str) -> dict:
    """Get CF-compliant metadata for a field name.
    
    Handles:
    - Both dot and underscore naming conventions
    - Prefixed fields (H00100..., KT273..., P_...)
    - Truncated field names
    """
    # Direct match
    if field_name in FA_METADATA:
        return FA_METADATA[field_name].copy()
    
    # Try with dots/underscores swapped
    underscore_name = field_name.replace('.', '_')
    if underscore_name in FA_METADATA:
        return FA_METADATA[underscore_name].copy()
    dot_name = field_name.replace('_', '.')
    if dot_name in FA_METADATA:
        return FA_METADATA[dot_name].copy()
    
    # Strip common prefixes (H00100, KT273, P_, etc.)
    import re
    stripped = re.sub(r'^(H\d+|KT\d+|P_|S\d+)', '', field_name)
    if stripped and stripped in FA_METADATA:
        return FA_METADATA[stripped].copy()
    stripped_underscore = stripped.replace('.', '_')
    if stripped_underscore in FA_METADATA:
        return FA_METADATA[stripped_underscore].copy()
    
    # Pattern matching - check if any known pattern is contained in the field name
    for pattern, meta in FA_METADATA.items():
        # Skip very short patterns to avoid false matches
        if len(pattern) < 5:
            continue
        if pattern in field_name:
            return meta.copy()
        # Also try the pattern with underscores
        pattern_underscore = pattern.replace('.', '_')
        if pattern_underscore in field_name:
            return meta.copy()
    
    # Try matching the start of field name (after prefix) to known patterns
    for pattern, meta in FA_METADATA.items():
        if len(pattern) < 5:
            continue
        if stripped.startswith(pattern[:min(len(pattern), len(stripped))]):
            return meta.copy()
    
    return {}


def apply_metadata_to_dataset(ds):
    """Apply metadata to all variables in a dataset."""
    for var_name in ds.data_vars:
        meta = get_metadata(var_name)
        if meta:
            ds[var_name].attrs.update(meta)
    return ds

